### ISSUE TITLE
Signatures outdated for game version 2023.07.06.0000.0000

### ISSUE THREAD

**Issue by NotNite** [ProjectMimer/xivr#13]
On game version 2023.07.06.0000.0000, xivr enables without problem, but fails to open the config GUI or respond to any commands:

```
2023-08-03 20:07:22.906 -04:00 [ERR] [xivr] Failed loading vr dll
Dalamud.Utility.Signatures.SignatureException: Failed to find Text signature "ScreenPointToRay1Hook" for xivr.xivr_hooks (E8 ?? ?? ?? ?? 80 BF 74 01 00 00 00)
   at Dalamud.Utility.Signatures.SignatureHelper.<>c__DisplayClass1_0.<Initialise>g__Invalid|4(String message, Boolean prepend, <>c__DisplayClass1_1&, <>c__DisplayClass1_2&) in C:\goatsoft\companysecrets\dalamud\Utility\Signatures\SignatureHelper.cs:line 68
   at Dalamud.Utility.Signatures.SignatureHelper.Initialise(Object self, Boolean log) in C:\goatsoft\companysecrets\dalamud\Utility\Signatures\SignatureHelper.cs:line 185
   at xivr.xivr_hooks.Initialize() in /work/repo/xivr/xivr_hooks.cs:line 279
   at xivr.xivr..ctor(DalamudPluginInterface pluginInterface, TitleScreenMenu titleScreenMenu) in /work/repo/xivr/xivr.cs:line 88
```

I'm not 100% confident, but `E8 ?? ?? ?? ?? 38 9F ?? ?? ?? ?? 74 25` should work as a replacement for this signature. Other signatures are failing, but they seem to only be warnings: `2023-08-03 20:07:22.716 -04:00 [WRN] [Dalamud] Failed to find Text signature "PushbackUIHook" for xivr.xivr_hooks (E8 ?? ?? ?? ?? EB 05 E8 ?? ?? ?? ?? 48 8B 5C 24 78)`

Note that the plugin still does not seem to function for me, even after fixing this signature. I am not well versed in this plugin's code enough to investigate further. It seems that there is [a new version of this plugin](https://github.com/ProjectMimer/xivr-Ex), but that also does not work for me (why is there two versions of the same plugin and one of them is third party???).

There seems to be reports in the XIVLauncher & Dalamud server of this plugin being broken since around mid-June. Maybe consider [temporarily disabling it](https://github.com/goatcorp/DalamudAssets/blob/master/UIRes/bannedplugin.json) in the future if such an occurrence happens again?

**Comment by NotNite** [comment]
PushbackUIHook seems to be `E8 ?? ?? ?? ?? EB 05 E8 ?? ?? ?? ?? 4C 8D 5C 24 ??`.

**Comment by NotNite** [comment]
This version of XIVR is still broken and does not work - it remains on the official Dalamud plugin repository nonfunctional. Is there perhaps any update on this? If the plugin continues to be in a broken state, it will probably either be manually disabled by a maintainer or automatically disabled come Patch 6.5.
